main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('polls/', views.polls_index, name='polls_index'),
    path('polls/<int:poll_id>/', views.polls_detail, name='polls_detail'),
    path('polls/create', views.PollCreate.as_view(), name='polls_create'),
    path('polls/<int:pk>/update', views.PollUpdate.as_view(), name='polls_update'),
    path('polls/<int:pk>/delete', views.PollDelete.as_view(), name='polls_delete'),
    path('polls/<int:poll_id>/add_option/', views.add_option, name='add_option'),
    path('polls/<int:poll_id>/update_option/<int:option_id>/', views.update_option, name='update_option'),
    path('accounts/signup', views.signup, name='signup'),
]

solepoll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils import timezone, dateformat

# Create your models here.

class Poll(models.Model):
  formatted_date = dateformat.format(timezone.now(), 'Y-m-d H:i')

  title = models.CharField(max_length=280)
  notes = models.TextField(max_length=500, blank=True)
  public = models.BooleanField(default=True)
  expired = models.BooleanField(default=False)
  expires = models.DateTimeField(default=formatted_date, null=True, blank=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return self.title

  def clean(self, *args, **kwargs):
    super(Poll, self).clean(*args, **kwargs)
    if self.expires:
      if self.expires < timezone.now():
        raise ValidationError('Expiration time must be later than now.')

  def get_absolute_url(self):
      return reverse("polls_detail", kwargs={"poll_id": self.id})


class Option(models.Model):
  title = models.CharField(max_length=100)
  count = models.PositiveIntegerField(default=0)
  poll = models.ForeignKey(Poll, on_delete=models.CASCADE)

  def __str__(self):
    return self.title

main_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Option, Poll
from .widgets import DateTimePickerInput

class OptionForm(ModelForm):
  class Meta:
    model = Option
    fields = ['title']

class PollDateTimeForm(ModelForm):
  class Meta:
    model = Poll
    fields = ['title', 'notes', 'public', 'expires']
    widgets = {
      'expires': DateTimePickerInput()
    }
    help_texts = {'expires': ('Clear date field for no expiration.')}

main_app/views.py
import requests
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Poll, Option
from .forms import OptionForm, PollDateTimeForm
from django.utils import timezone
from django.db.models import Sum


CHART_COLORS = [
  'ffcd00', 
  'ff3051', 
  '5eac24', 
  '1869b7',
  '6a4c93',
  '17c3b2',
  'e85d04',
  'ef476f',
  '80ed99',
  '073b4c',
  '00bbf9',
  '7678ed',
  '89b0ae',
  '840032',
  'ffdc5e'
]

def chart_url_builder(options):
  url_str = 'https://image-charts.com/chart?chbr=6&chco='
  chco = ''
  chd = ''
  chdl = ''
  chm = ''

  i = 0
  for option in options:
    chco += (CHART_COLORS[i] + ',')

    if (i == len(options) - 1):
      chd += str(option.count)
    else:
      chd += (str(option.count) + '|')
    
    chdl += option.title + '|'
    chm += f'N,000000,{i},,10|'

    i += 1

  url_str += chco
  url_str += '&chd=t:'
  url_str += chd
  url_str += '&chdl='
  url_str += chdl
  url_str += '&chdls=000000,15&chds=0,50000&chm='
  url_str += chm
  url_str += '&chma=0,0,10,10&chs=700x200&cht=bhg&chxs=0,000000,0,0,_&chxt=y&chan&chf=bg,s,EFEFEF11'

  return url_str


# Create your views here.

class Home(LoginView):
  template_name = 'home.html'

def about(request):
  return render(request, 'about.html')

def polls_index(request):
  all_polls = Poll.objects.all()
  for poll in all_polls:
    if poll.expires:
      if (poll.expires < timezone.now()):
        poll.expired = True
        poll.save()
  public_polls = Poll.objects.filter(public=True).filter(expired=False).order_by('expired')
  expired_polls = Poll.objects.filter(expired=True).order_by('expired')
  user_polls = []
  if(request.user.id):
    user_polls = Poll.objects.filter(user=request.user).order_by('expired')
  return render(request, 'polls/index.html', {
    'public_polls': public_polls,
    'user_polls': user_polls,
    'expired_polls': expired_polls
  })

def polls_detail(request, poll_id):
  poll = Poll.objects.get(id=poll_id)
  options = Option.objects.filter(poll=poll_id).order_by('count')
  chart_url = ''
  
  if (options):
    chart_url = chart_url_builder(options)

  if poll.expires:
    if (poll.expires < timezone.now()):
      poll.expired = True
      poll.save()

  option_form = OptionForm()
  total_votes = Option.objects.filter(poll=poll_id).aggregate(Sum('count'))['count__sum']
  return render(request, 'polls/detail.html', {
    'poll': poll,
    'option_form': option_form,
    'total_votes': total_votes,
    'chart_url': chart_url,
  })

@login_required
def add_option(request, poll_id):
  form = OptionForm(request.POST)
  if form.is_valid():
    new_option = form.save(commit=False)
    new_option.poll_id = poll_id
    new_option.save()
  return redirect('polls_detail', poll_id=poll_id)

@login_required
def update_option(request, poll_id, option_id):
  option = Option.objects.get(id=option_id)
  option.count += 1
  option.save()
  return redirect('polls_detail', poll_id=poll_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('polls_index')
    else:
      error_message = 'Invalid sign-up => try again'
  
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'signup.html', context)


class PollCreate(CreateView):
  form_class = PollDateTimeForm
  model = Poll

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)


class PollUpdate(LoginRequiredMixin, UpdateView):
  form_class = PollDateTimeForm
  model = Poll

class PollDelete(LoginRequiredMixin, DeleteView):
  model = Poll
  success_url = '/polls/'

main_app/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/about.css' %}"/>
{% endblock %}

{% block content %}

<div class="container mt-5">
<h1>About Sole-Poll</h1>
<hr />
<h2>
  Create simple polls!
</h2>
</div>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
    rel="shortcut icon"
    type="image/png"
    href="{% static 'images/favicon.ico' %}"
  >
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
  <title>Sole-Poll</title>
  {% block head %}
  {% endblock %}
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <header>
    <div class="header-logo-container">
      <a href="/">
        <span>
          Sole-Poll
        </span>
      </a>
    </div>
    <nav>
      <ul>
        {% if user.is_authenticated %}
          <li><a href="{% url 'polls_index' %}">All Polls</a></li>
          <li><a href="{% url 'polls_create' %}">Create</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'polls_index' %}">All Polls</a></li>
          <li><a href="{% url 'polls_create' %}">Create</a></li>
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'home' %}">Login</a></li>
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}

<section class="logo-container">
  <div class="poll-container">
    <img src="{% static 'images/poll.png' %}" alt="poll logo" />
    <h1>Sole-Poll</h1>
  </div>
</section>

{% if not user.is_authenticated %}
  <section>
    <form action="{% url 'home' %}" method="post" class="login">
      <h1>Login</h1>
      {% csrf_token %}
      {{ form.as_p }}
      <input type="hidden" name="next" value="{{ next }}">
      <button type="submit" class="btn submit">Login</button>
    </form>
  </section>
{% endif %}

{% endblock %}

main_app/templates/main_app/poll_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/confirm_delete.css' %}"
/>
{% endblock %}

{% block content %}

<div class="container mt-5">
  <div class="page-header">
    <h1>Delete Poll?</h1>
  </div>
  <h2>Are you sure you want to delete this poll?</h2>

  <form action="" method="POST" class="form mt-5">
    {% csrf_token %}
    <a 
      href="{% url 'polls_detail' poll.id %}" 
      class="btn secondary"
    >
      Cancel
    </a>
    <button type="submit" class="btn danger">Yes - Delete!</button>
  </form>
</div>

{% endblock %}

main_app/templates/main_app/poll_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class='container mt-5'>
  <div class="page-header">
    {% if poll %}
      <h1>Edit this Poll</h1>
    {% else %}
      <h1>Create a Poll</h1>
    {% endif %}
    <img src="{% static 'images/poll.png' %}" alt="poll logo"/>
  </div>
  <form action="" method="post" class="form-container">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit mt-4">Submit</button>
  </form>
</div>

{% endblock %}

main_app/templates/polls/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet" 
  type="text/css" 
  href="{% static 'css/polls/poll-detail.css' %}"
/>
<script src="{% static 'scripts/poll_detail.js' %}"></script>
{% endblock %}

{% block content %}

<div class="container details-container mt-5">
  
  <div class="row">
    <div class="poll-details">
      <h1>{{ poll.title }}</h1>
      {% if poll.notes %}
        <h2>{{ poll.notes }}</h2>
      {% endif %}
      {% if not poll.expired %}
        {% if poll.expires %}
          <h3>Closes: {{ poll.expires|timeuntil }}</h3>
        {% endif %}
      {% else %}
        <h3 class="fw-bolder fs-2 fst-italic text-warning">Poll Ended</h3>
      {% endif %}
      <button 
        id="linkBtn"
        onclick="copyLink()"
        class="mt-4 w-25 fs-2 fw-bolder button-25"
        style="float: none; margin: 0 auto;"
        >Copy Poll Link</button>
    </div>
  </div>

  <div class="row mt-5">
    <div class="options-container">
      <section class="options">
        <div class="subsection-title">
          <h2>Options</h2>
        </div>
        {% if user.id == poll.user_id %}
          {% if not poll.expired %}
            <h3>Add an Option</h3>
            <form
              action="{% url 'add_option' poll.id %}"
              method="post" 
              class="subsection-content m-2"
            >
              {% csrf_token %}
              {{ option_form.as_p }}
              <button type="submit" class="btn m-4">Add Option</button>
            </form>
          {% else %}
            <h3 class="text-warning">Poll is closed</h3>
          {% endif %}
        {% endif %}
        {% if poll.option_set.all.count %}
          <table>
            <thead>
              <tr><th>Options</th><th>Results</th><th></th></tr>
            </thead>
            <tbody>
              {% for option in poll.option_set.all|dictsortreversed:"count" %}
                <tr>
                  <td>{{ option.title }}</td>
                  <td>{{ option.count }}</td>
                  <td>
                    {% if not poll.expired %}
                      <form action="{% url 'update_option' poll.id option.id %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="button-29">Vote</button>
                      </form>
                    {% endif %}
                  </td>
                </tr>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <td><span class=tfooter>Total Votes:</span></td>
                <td><span class=tfooter>{{ total_votes }}</span></td>
                <td></td>
              </tr>
            </tfoot>
          </table>
        {% else %}
          <div class="subsection-content">
            <p>No options yet.</p>
          </div>
        {% endif %}
      </section>
    </div>
  </div>

  <div class="image-container">
    {% if chart_url %}
      <img src="{{ chart_url }}" alt="chart with poll results">
    {% endif %}
  </div>

  {% if user.id == poll.user_id %}
    <div class="poll-actions">
      <a href="{% url 'polls_update' poll.id %}" class="btn warn">Edit</a>
      <a href="{% url 'polls_delete' poll.id %}" class="btn danger">Delete</a>
    </div>
  {% endif %}
</div>

{% endblock %}

main_app/templates/polls/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link 
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/polls/poll-index.css' %}"
/>
{% endblock %}

{% block content %}

  <div class="container main-container mt-5">
    <section class="page-header">
      <h1>Available Polls</h1>
    </section>

    <div class="row p-2">
      <ul class="list-group">
        {% for poll in public_polls %}
          <li class="list-group-item d-flex justify-content-between align-items-start">
            <a href="{% url 'polls_detail' poll.id %}">
              <div class="ms-2 me-auto">
                <h3>{{ poll.title }}</h3>
                <h4>{{ poll.notes }}</h4>
                {% if poll.expires %}
                  <h4>Closes ~ {{ poll.expires|timeuntil }}</h4>
                {% endif %}
              </div>
            </a>
          </li>
        {% endfor %}
      </ul>
    </div>

    <div class="row">
      {% if user.is_authenticated %}
      <p>
        <button class="btn collapse-btn mt-5" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-user-polls" aria-expanded="false" aria-controls="collapse-user-polls">
          Your Polls
        </button>
      </p>
      <div class="collapse" id="collapse-user-polls">
        <ul class="list-group">
          {% for poll in user_polls %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
              <a href="{% url 'polls_detail' poll.id %}">
                <div class="ms-2 me-auto">
                  <h3>{{ poll.title }}</h3>
                  <h4>{{ poll.notes }}</h4>
                  {% if poll.expires %}
                    <h4>Closes ~ {{ poll.expires|timeuntil }}</h4>
                  {% endif %}
                </div>
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}
    </div>

    <div class="row">
      <p>
        <button class="btn collapse-btn mt-5" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-expired" aria-expanded="false" aria-controls="collapse-expired">
          Show Closed Polls
        </button>
      </p>
      <div class="collapse" id="collapse-expired">
        <ul class="list-group">
          {% for poll in expired_polls %}
            <li class="list-group-item d-flex justify-content-between align-items-start">
              <a href="{% url 'polls_detail' poll.id %}">
                <div class="ms-2 me-auto">
                  <h3>{{ poll.title }}</h3>
                  <h4>{{ poll.notes }}</h4>
                </div>
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}"/>
{% endblock %}

{% block content %}

<div class="container mt-5">
  <div class="page-header">
    <h1>Sign Up</h1>
  </div>
  {% if error_message %}
    <p class="red-text">{{ error_message }}</p>
  {% endif %}
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit mt-4">Submit</button>
  </form>
</div>

{% endblock %}